name: CEB Outage Checker

on:
  schedule:
    - cron: "*/1 * * * *"
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  check_outages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Download previous notification history
        uses: dawidd6/action-download-artifact@v9
        with:
          name: notification-history
          path: .
          if_no_artifact_found: warn
      
      - name: Run outage checker
        env:
          # Hardcoded credentials (NOT RECOMMENDED)
          CEB_USERNAME: "jagath1803"
          CEB_PASSWORD: "Gsy@1539Sg"
          NTFY_URL: "https://ntfy.sh/manilkanotifi"
        run: python ceb_outage_checker.py
        
      - name: Save notification history
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: notification-history
          path: notification_history.json
          retention-days: 90
          
      - name: Save outage data
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: outage-data
          path: ceb_outages.json
          retention-days: 7
