name: CEB Outage Checker

on:
  # Triggers the workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Download previous notification history
        uses: dawidd6/action-download-artifact@v9
        with:
          name: notification-history
          path: .
          if_no_artifact_found: warn
      
      - name: Run outage checker
        env:
          CEB_USERNAME: ${{ secrets.CEB_USERNAME }}
          CEB_PASSWORD: ${{ secrets.CEB_PASSWORD }}
          NTFY_URL: ${{ secrets.NTFY_URL }}
          CEB_ACCOUNTS: ${{ secrets.CEB_ACCOUNTS }}
        run: python ceb_outage_checker.py
          
      - name: Save notification history
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: notification-history
          path: notification_history.json
          retention-days: 90
          
      - name: Save outage data
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: outage-data
          path: ceb_outages.json
          retention-days: 7
